"""arrumando 

Revision ID: 3a7109b510b8
Revises: da8a07787beb
Create Date: 2020-05-31 18:14:36.734457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a7109b510b8'
down_revision = 'da8a07787beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(length=128), nullable=True),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('complement', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_complement'), 'address', ['complement'], unique=False)
    op.create_index(op.f('ix_address_neighborhood'), 'address', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_address_number'), 'address', ['number'], unique=False)
    op.create_index(op.f('ix_address_street'), 'address', ['street'], unique=False)
    op.alter_column('person', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('person', 'modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('users', sa.Column('creation_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('modification_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modification_date')
    op.drop_column('users', 'creation_date')
    op.alter_column('person', 'modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('person', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_address_street'), table_name='address')
    op.drop_index(op.f('ix_address_number'), table_name='address')
    op.drop_index(op.f('ix_address_neighborhood'), table_name='address')
    op.drop_index(op.f('ix_address_complement'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
