"""nova tabela pessoa

Revision ID: 4a6d017d75cd
Revises: 83009c7c25bc
Create Date: 2020-05-30 17:53:38.289822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6d017d75cd'
down_revision = '83009c7c25bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.String(length=128), nullable=True),
    sa.Column('_type', sa.String(length=128), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('modification_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person__type'), 'person', ['_type'], unique=False)
    op.create_index(op.f('ix_person_cnpj'), 'person', ['cnpj'], unique=False)
    op.create_index(op.f('ix_person_company_name'), 'person', ['company_name'], unique=False)
    op.create_index(op.f('ix_person_cpf'), 'person', ['cpf'], unique=False)
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.create_index(op.f('ix_person_surname'), 'person', ['surname'], unique=False)
    op.add_column('users', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'person_id')
    op.drop_index(op.f('ix_person_surname'), table_name='person')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_index(op.f('ix_person_cpf'), table_name='person')
    op.drop_index(op.f('ix_person_company_name'), table_name='person')
    op.drop_index(op.f('ix_person_cnpj'), table_name='person')
    op.drop_index(op.f('ix_person__type'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
