"""novas tabelas para permissão por sistemas

Revision ID: 57ded67ba129
Revises: be7035c16fa3
Create Date: 2020-09-15 21:56:01.214154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ded67ba129'
down_revision = 'be7035c16fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_name'), 'system', ['name'], unique=True)
    op.create_index(op.f('ix_system_url'), 'system', ['url'], unique=False)
    op.create_table('profileSystem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileSystem_name'), 'profileSystem', ['name'], unique=False)
    op.create_table('systemPermission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemPermission_name'), 'systemPermission', ['name'], unique=False)
    op.create_table('profilePermission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_system_id', sa.Integer(), nullable=False),
    sa.Column('system_permission_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_system_id'], ['profileSystem.id'], ),
    sa.ForeignKeyConstraint(['system_permission_id'], ['systemPermission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userProfileSystem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profileSytem_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profileSytem_id'], ['profileSystem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userProfileSystem')
    op.drop_table('profilePermission')
    op.drop_index(op.f('ix_systemPermission_name'), table_name='systemPermission')
    op.drop_table('systemPermission')
    op.drop_index(op.f('ix_profileSystem_name'), table_name='profileSystem')
    op.drop_table('profileSystem')
    op.drop_index(op.f('ix_system_url'), table_name='system')
    op.drop_index(op.f('ix_system_name'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
