"""nova coluna description na tabela profileSystem

Revision ID: 6a6e0bbf51d7
Revises: dc1b72f44433
Create Date: 2020-10-13 11:23:29.170834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6e0bbf51d7'
down_revision = 'dc1b72f44433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profileSystem', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profileSystem', 'description')
    # ### end Alembic commands ###
