"""coluna url não requerida na tabela system

Revision ID: 6d01840b9f84
Revises: 6a6e0bbf51d7
Create Date: 2020-10-13 18:12:40.955234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d01840b9f84'
down_revision = '6a6e0bbf51d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
