"""coluna system_id na tabela UserProfileSystem

Revision ID: d01b02d6d040
Revises: 6d01840b9f84
Create Date: 2020-10-20 08:42:28.000119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01b02d6d040'
down_revision = '6d01840b9f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userProfileSystem', sa.Column('system_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userProfileSystem', 'system', ['system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userProfileSystem', type_='foreignkey')
    op.drop_column('userProfileSystem', 'system_id')
    # ### end Alembic commands ###
