"""mudança no nome da coluna _type para type

Revision ID: da8a07787beb
Revises: 4a6d017d75cd
Create Date: 2020-05-30 17:56:27.941856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8a07787beb'
down_revision = '4a6d017d75cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('type', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_person_type'), 'person', ['type'], unique=False)
    op.drop_index('ix_person__type', table_name='person')
    op.drop_column('person', '_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('ix_person__type', 'person', ['_type'], unique=False)
    op.drop_index(op.f('ix_person_type'), table_name='person')
    op.drop_column('person', 'type')
    # ### end Alembic commands ###
