"""empty message

Revision ID: dc1b72f44433
Revises: 2dd809fc3063
Create Date: 2020-10-06 16:43:59.985286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc1b72f44433'
down_revision = '2dd809fc3063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userProfileSystem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_system_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_system_id'], ['profileSystem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userProfileSytem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userProfileSytem',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userProfileSytem_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modification_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('profile_system_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_system_id'], ['profileSystem.id'], name='userProfileSytem_profile_system_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='userProfileSytem_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='userProfileSytem_pkey')
    )
    op.drop_table('userProfileSystem')
    # ### end Alembic commands ###
